name: helm-chart-test

on:
  pull_request:
    types: [opened, synchronize]
    branches:
      - main

jobs:
  get-chart-location:
    runs-on: ubuntu-latest
    outputs:
      chart_location: ${{ steps.vars.outputs.chart_location }}
    steps:
      - name: get pull request ref
        id: get_pull_request_ref
        uses: octokit/request-action@v2.x
        with:
          route: GET /repos/:repository/pulls/:pr_id
          repository: ${{ github.repository }}
          pr_id: ${{ github.event.pull_request.number }}
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

      - name: vars
        id: vars
        run: echo "::set-output name=chart_location::$(echo "${{ fromJson(steps.get_pull_request_ref.outputs.data).body }}" | grep path | awk '{print $4}')"

      - name: service-id
        id: service-id
        run: echo "::set-output name=service-id::$(echo "${{ fromJson(steps.get_pull_request_ref.outputs.data).body }}" | grep service | awk '{print $4}')"

      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          version: 'latest'
        id: install

      - name: install kubeval
        run: helm plugin install https://github.com/instrumenta/helm-kubeval

      - uses: actions/checkout@master

      - name: Check dev-values existence
        id: check_files_dev
        uses: andstor/file-existence-action@v1
        with:
          files: " ${{ steps.vars.outputs.chart_location }}/dev.values.yaml"

      - name: test6
        id: test6
        if: steps.check_files_dev.outputs.files_exists == 'true'
        uses: igabaydulin/helm-check-action@0.1.4
        env:
          CHART_LOCATION: ${{ steps.vars.outputs.chart_location }}
          CHART_VALUES: ${{ steps.vars.outputs.chart_location }}/dev.values.yaml

      - name: Check stage-values existence
        id: check_files_stage
        uses: andstor/file-existence-action@v1
        with:
          files: " ${{ steps.vars.outputs.chart_location }}/stage.values.yaml"

      - name: test7
        id: test7
        if: steps.check_files_stage.outputs.files_exists == 'true'
        uses: igabaydulin/helm-check-action@0.1.4
        env:
          CHART_LOCATION: ${{ steps.vars.outputs.chart_location }}
          CHART_VALUES: ${{ steps.vars.outputs.chart_location }}/stage.values.yaml

      - name: Check prod-values existence
        id: check_files_prod
        uses: andstor/file-existence-action@v1
        with:
          files: " ${{ steps.vars.outputs.chart_location }}/prod.values.yaml"

      - name: test8
        id: test8
        if: steps.check_files_prod.outputs.files_exists == 'true'
        uses: igabaydulin/helm-check-action@0.1.4
        env:
          CHART_LOCATION: ${{ steps.vars.outputs.chart_location }}
          CHART_VALUES: ${{ steps.vars.outputs.chart_location }}/prod.values.yamlocation.outputs.chart_location }}/prod.values.yaml)"

      - name: kubernetes yaml syntax
        if: ${{ always() }}
        run: helm kubeval ${{ steps.vars.outputs.chart_location }}

      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Scan Helm Charts
        run: |
          pip install -U checkov
          curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3
          chmod 700 get_helm.sh
          ./get_helm.sh
          cd ${{ steps.vars.outputs.chart_location }}
          helm template --debug -f stage.values.yaml ${{ steps.service-id.outputs.service-id }} . >> temp.yaml
          checkov -f temp.yaml --framework kubernetes || true

      - name: Comment on PR
        id: test9
        if: ${{ success() }}
        uses: allthatjazzleo/actions-pull-request-add-comment@master
        with:
          message: |-
            Helm syntex & Kubernetes schemas ë¬¸ì œ ì—†ìŠµë‹ˆë‹¤! ğŸš€
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

      - name: Comment on PR
        id: test10
        if: ${{ failure() }}
        uses: allthatjazzleo/actions-pull-request-add-comment@master
        with:
          message: |-
            Helm syntax or Kubernetes schemas ì²´í¬í•˜ëŠ” ë„ì¤‘ ë¬¸ì œê°€ ë°œìƒí–ˆìŠµë‹ˆë‹¤. ì•„ë˜ ë§í¬ì—ì„œ í™•ì¸í•´ ì£¼ì„¸ìš”. ğŸ˜¢
            [https://github.com/${{github.repository}}/actions/runs/${{github.run_id}}](https://github.com/${{github.repository}}/actions/runs/${{github.run_id}})
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

